version: "3.8"
services:
  db:
    image: "postgres:12"
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=next-prisma-auth-tutorial
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=next-prisma-auth-tutorial
